on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test install backend on Debian 11
    steps:
      - name: Test install backend
        uses: actions/test-install-backend@v1
